export const browserCoreExamples = [
  "secretclaw browser status",
  "secretclaw browser start",
  "secretclaw browser stop",
  "secretclaw browser tabs",
  "secretclaw browser open https://example.com",
  "secretclaw browser focus abcd1234",
  "secretclaw browser close abcd1234",
  "secretclaw browser screenshot",
  "secretclaw browser screenshot --full-page",
  "secretclaw browser screenshot --ref 12",
  "secretclaw browser snapshot",
  "secretclaw browser snapshot --format aria --limit 200",
  "secretclaw browser snapshot --efficient",
  "secretclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "secretclaw browser navigate https://example.com",
  "secretclaw browser resize 1280 720",
  "secretclaw browser click 12 --double",
  'secretclaw browser type 23 "hello" --submit',
  "secretclaw browser press Enter",
  "secretclaw browser hover 44",
  "secretclaw browser drag 10 11",
  "secretclaw browser select 9 OptionA OptionB",
  "secretclaw browser upload /tmp/file.pdf",
  'secretclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "secretclaw browser dialog --accept",
  'secretclaw browser wait --text "Done"',
  "secretclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "secretclaw browser console --level error",
  "secretclaw browser pdf",
];
